name: "Multi event pipeline / workflow" # Name of the pipeline

on:

  push: # Event: Whenever a push is made to the repository on the master / test branch
    branches:
      - master
      - test

  pull_request: # Event: Whenever a pull request is made to the repository
    branches:
      - master
  
  workflow_dispatch: # Event: Manually trigger the workflow from the GitHub Actions tab in the repository
      

jobs:

  on-push: # Job 1
    if: github.event_name == 'push' # Run this job only if the event is a push
    runs-on: ubuntu-latest

    steps: # Steps to be executed in the job

      - name: "Running on master/test push" # Step 1
        run: echo "Running on master/test push"

  on-pull-request: # Job 2
    if: github.event_name == 'pull_request' # Run this job only if the event is a pull request
    runs-on: ubuntu-latest

    steps: # Steps to be executed in the job

      - name: "Running on pull request" # Step 1
        run: echo "Running on pull request"

  on-workflow-dispatch: # Job 3
    if: github.event_name == 'workflow_dispatch' # Run this job only if the event is a manual trigger
    runs-on: ubuntu-latest

    steps: # Steps to be executed in the job

      - name: "Running on workflow dispatch" # Step 1
        run: echo "Running on workflow dispatch"